### ISSUE TITLE
`packages/api-mocks-vitest` is never built or typechecked in CI, and its build is broken

### ISSUE THREAD

**Issue by sAchin-680** [podman-desktop/podman-desktop#19368]
### Task content

`packages/api-mocks-vitest` is not covered by any CI job. It appears in neither the root `build` script, the root `typecheck` script, nor
`.github/workflows/pr-check.yaml`. Nothing compiles it.

As a result its build has been broken, unnoticed, since the package was added in #17309. On a clean checkout of `main` (5a596e35c6b), running the package's own build command fails with 5 TypeScript errors, all in `src/vitest-generate-api-global-setup.spec.ts`:

    src/vitest-generate-api-global-setup.spec.ts(26,4): error TS2769: No overload matches this call.
    src/vitest-generate-api-global-setup.spec.ts(89,30): error TS2345: Argument of type 'Buffer<ArrayBufferLike>' is not assignable to parameter of type 'string | NonSharedBuffer'.
    src/vitest-generate-api-global-setup.spec.ts(90,30): error TS2345: (same)
    src/vitest-generate-api-global-setup.spec.ts(111,30): error TS2345: (same)
    src/vitest-generate-api-global-setup.spec.ts(112,30): error TS2345: (same)

To reproduce:

    cd packages/api-mocks-vitest
    pnpm build

The `TS2769` is the `vi.mock` of `node:fs/promises`: the mock factory's `default` is missing ~28 members of the real module. The four `TS2345`s are `Buffer<ArrayBufferLike>` vs `string | NonSharedBuffer`.

Worth noting the tests themselves pass — `vitest run packages/api-mocks-vitest` is 6/6 green. Vitest transpiles without typechecking, which is why this stayed invisible.

Suggested work:

- add the package to the root `typecheck` script so regressions are caught
- fix the 5 type errors in the spec file

### Additional context

Found while wiring the package into the npm publish workflow (#19365). That PR needs the package to build in CI, and works around this with a build-only `tsconfig.build.json` that excludes spec files from compilation. That unblocks publishing but leaves the spec files unchecked, so the underlying issue remains.
